apiVersion: v1
kind: ConfigMap
metadata:
  name: mosquitto-config
  namespace: edgeapi-mqtt
data:
  mosquitto.conf: |
    # DO NOT USE IN PRODUCTION
    allow_anonymous true

    # MQTT with TLS (MQTTS)
    listener 8883
    protocol mqtt
    