kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: aggregated-edgecontroller-clusterrole
rules:
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["get", "watch", "list"]
- apiGroups: ["org.redhat.edgeapi"]
  resources: ["edgedevices"]
  verbs: ["get", "watch", "list"]
