apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: edgeapi-controller-clusterrolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: aggregated-edgecontroller-clusterrole
subjects:
- kind: ServiceAccount
  name: edgeapicontroller
  namespace: edgeapi
