---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: edge-controller
  namespace: edgeapi
  labels:
    controller: "true"
spec:
  selector:
    matchLabels:
      controller: "true"
  replicas: 1
  template:
    metadata:
      labels:
        controller: "true"
    spec:
      serviceAccountName: edgeapicontroller
      containers:
      - name: edge-manager
        image: docker.io/localhost/edge-manager:latest
        imagePullPolicy: Never
        args:
        resources:
          requests:
            cpu: 100m
            memory: 200Mi
          limits:
            cpu: 100m
            memory: 300Mi
