apiVersion: apps/v1
kind: Deployment
metadata:
  name: edge-api-server
  namespace: edgeapi
  labels:
    apiserver: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      apiserver: "true"
  template:
    metadata:
      labels:
        apiserver: "true"
    spec:
      serviceAccountName: edgeapiserver
      containers:
      - name: edge-api-server
        image: docker.io/localhost/edge-api-server:latest
        imagePullPolicy: Never
        args: [ 
          "--etcd-servers=http://localhost:2379",
          "--cert-dir=/tmp",
          ]
      - name: etcd
        image: gcr.io/etcd-development/etcd:v3.5.11
