apiVersion: apiregistration.k8s.io/v1
kind: APIService
metadata:
  name: v1alpha1.org.redhat.edgeapi
spec:
  insecureSkipTLSVerify: true
  group: org.redhat.edgeapi
  groupPriorityMinimum: 1000
  versionPriority: 15
  service:
    name: api
    namespace: edgeapi
  version: v1alpha1
